# Generated by Django 4.2.5 on 2023-09-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('roll', models.CharField(max_length=10)),
                ('level', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=50)),
            ],
        ),
    ]
